# Generated by Django 4.0.6 on 2023-01-12 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Product',
            new_name='product',
        ),
    ]
