# Generated by Django 4.0.6 on 2023-01-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.CharField(default='address', max_length=300),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('order-placed', 'order-placed'), ('on-transit', 'on-transit'), ('order-cancelled', 'order-cancelled'), ('order-delivered', 'order-delivered')], default='paypal', max_length=50),
        ),
    ]
