# Generated by Django 4.0.6 on 2023-01-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Paypal', 'Paypal'), ('cash-on-delivery', 'cash-on-delivery'), ('bank-Transfer', 'bank-Transfer')], default='Paypal', max_length=50),
        ),
    ]
